vector_store:
  # 向量数据库(chroma)的集合名称
  collection_name: "xiaoxizi_knowledge"
  # 文档目录
  docs_dir: "doc/话术"
  # 模型持久化路径
  persist_path: "models/chroma"
embedding:
  # 嵌入模型名称,更快可以换可以换 "BAAI/bge-large-zh-v1.5"，但需要至少8G内存
  model_name: "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
  # 分块大小
  chunk_size: 512
  # 分块重叠
  chunk_overlap: 50
  # 批量处理大小 2核4G建议8
  batch_size: 8